-- Create RxNorm tables in a SQLite database.
-- Adapted from their scripts/mysql/Table_scripts_mysql_rxn.sql

DROP INDEX IF EXISTS IDX_RXNCONSO_RXCUI;
CREATE INDEX IDX_RXNCONSO_RXCUI ON RXNCONSO(RXCUI);

DROP INDEX IF EXISTS IDX_RXNCONSO_RXAUI;
CREATE INDEX IDX_RXNCONSO_RXAUI ON RXNCONSO(RXAUI);

DROP INDEX IF EXISTS IDX_RXNCONSO_SAB;
CREATE INDEX IDX_RXNCONSO_SAB ON RXNCONSO(SAB);

DROP INDEX IF EXISTS IDX_RXNSAT_RXCUI;
CREATE INDEX IDX_RXNSAT_RXCUI ON RXNSAT(RXCUI);

DROP INDEX IF EXISTS IDX_RXNSAT_SAB;
CREATE INDEX IDX_RXNSAT_SAB ON RXNSAT(SAB);

DROP INDEX IF EXISTS IDX_RXNREL_RXCUI;
CREATE INDEX IDX_RXNREL_RXCUI ON RXNREL(RXCUI1);

DROP INDEX IF EXISTS IDX_RXNREL_RXCUI;
CREATE INDEX IDX_RXNREL_RXCUI ON RXNREL(RXCUI2);
